<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tuber" nsURI="http://www.example.org/tuber" nsPrefix="tuber">
  <eClassifiers xsi:type="ecore:EClass" name="TUber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" upperBound="-1"
        eType="#//Agent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rides" upperBound="-1"
        eType="#//Ride" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" lowerBound="1" eType="#//City"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//AppUser" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revenue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//AppUser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" upperBound="-1"
        eType="#//Payment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spendings" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Driver" eSuperTypes="#//AppUser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earnings" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppUser" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportCall" upperBound="-1"
        eType="#//HelpCentreCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//RideStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PaymentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HelpCentreCall" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//TicketStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VehicleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lt" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lg" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" lowerBound="1" eType="#//City"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="City">
    <eLiterals name="WIEN"/>
    <eLiterals name="SALZBURG" value="1"/>
    <eLiterals name="LINZ" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TicketStatus">
    <eLiterals name="RESOLVED"/>
    <eLiterals name="PENDING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IssueType">
    <eLiterals name="PAYMENT"/>
    <eLiterals name="SAFETY" value="1"/>
    <eLiterals name="ACCOUNT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RideStatus">
    <eLiterals name="IDLE"/>
    <eLiterals name="REQUESTED" value="1"/>
    <eLiterals name="ONGOING" value="2"/>
    <eLiterals name="COMPLETED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PaymentType">
    <eLiterals name="CREDITCARD"/>
    <eLiterals name="APPLEPAY" value="1"/>
    <eLiterals name="PAYPAL" value="2"/>
    <eLiterals name="CASH" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VehicleType">
    <eLiterals name="MOTORBIKE"/>
    <eLiterals name="CAR" value="1"/>
    <eLiterals name="LUXURY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ride">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1"
        upperBound="-1" eType="#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1"
        eType="#//Driver"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//RideStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" eType="#//Payment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sharing" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyIssue" eSuperTypes="#//HelpCentreCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ride" lowerBound="1" eType="#//Ride"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentIssue" eSuperTypes="#//HelpCentreCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ride" lowerBound="1" eType="#//Ride"/>
  </eClassifiers>
</ecore:EPackage>
